$schema: https://json-schema.org/draft/2020-12/schema
title: ADA TEM Product Profile
description: Technique-specific profile for Transmission Electron Microscopy (TEM) products. Extends the base ADA product
  profile with constraints on valid TEM component types.
allOf:
- $ref: ../adaProduct/schema.yaml
- type: object
  properties:
    schema:additionalType:
      description: Must include a TEM product type identifier.
      contains:
        enum:
        - Transmission Electron Microscopy (TEM) Image
        - Transmission Electron Microscopy (TEM) Patterns Image
        - Scanning Transmission Electron Microscopy (STEM) Image
        - Scanning Transmission Electron Microscopy Energy Dispersive X-ray Spectroscopy (STEMEDS) Cube
        - Scanning Transmission Electron Microscopy Energy Dispersive X-ray Spectroscopy (STEMEDS) Tabular
        - Scanning Transmission Electron Microscopy Energy Dispersive X-ray Spectroscopy (STEMEDS) Tomography
        - Scanning Transmission Electron Microscopy Electron Energy-loss Spectra (STEMEELS) Cube
        - Scanning Transmission Electron Microscopy Electron Energy-loss Spectra (STEMEELS) Tabular
        - Transmission Electron Microscopy
    schema:distribution:
      description: Distribution items for adaTEM. Archive hasPart items must have ada:componentType from technique-specific
        or universal values.
      type: array
      items:
        type: object
        properties:
          schema:hasPart:
            items:
              type: object
              properties:
                ada:componentType:
                  anyOf:
                  - enum:
                    - ada:TEMImage
                    - ada:TEMPatternsImage
                    - ada:TEMEDSImageCollection
                    - ada:STEMImage
                    - ada:STEMEDSTabular
                    - ada:STEMEDSCube
                    - ada:STEMEDSTomo
                    - ada:STEMEELSTabular
                    - ada:STEMEELSCube
                  - ? ''
                    : ../adaProduct/schema.yaml#//universalComponentType
    schema:subjectOf:
      properties:
        dcterms:conformsTo:
          contains:
            type: object
            properties:
              '@id':
                const: 'https://w3id.org/geochem/metadata/profiles/adaTEM'
