$schema: https://json-schema.org/draft/2020-12/schema
title: ADA VLM Product Profile
description: Technique-specific profile for Visible Light Microscopy (VLM) products. Extends the base ADA product profile
  with constraints on valid VLM component types.
allOf:
- $ref: ../adaProduct/schema.yaml
- type: object
  properties:
    schema:additionalType:
      description: Must include a VLM product type identifier.
      contains:
        enum:
        - Visible Light Microscopy (VLM) Image
        - Basemap
        - Visible Light Microscopy
    schema:distribution:
      description: Distribution items for adaVLM. Archive hasPart items must have ada:componentType from technique-specific
        or universal values.
      type: array
      items:
        type: object
        properties:
          schema:hasPart:
            items:
              type: object
              properties:
                ada:componentType:
                  anyOf:
                  - enum:
                    - ada:VLMImage
                    - ada:VLMImageCollection
                  - ? ''
                    : ../adaProduct/schema.yaml#//universalComponentType
    schema:subjectOf:
      properties:
        dcterms:conformsTo:
          contains:
            type: object
            properties:
              '@id':
                const: 'https://w3id.org/geochem/metadata/profiles/adaVLM'
