$schema: https://json-schema.org/draft/2020-12/schema
title: ADA PSFD Product Profile
description: Technique-specific profile for Particle Size-Frequency Distribution (PSFD) products. Extends the base ADA product
  profile with constraints on valid PSFD component types and detailPSFD requirements.
allOf:
- $ref: ../adaProduct/schema.yaml
- type: object
  properties:
    schema:additionalType:
      description: Must include a PSFD product type identifier.
      contains:
        enum:
        - Particle Size Frequency Distribution (PSFD)
        - Particle Size Frequency Distribution
    schema:distribution:
      description: Distribution items for adaPSFD. Archive hasPart items must have ada:componentType from technique-specific
        or universal values.
      type: array
      items:
        type: object
        properties:
          schema:hasPart:
            items:
              type: object
              properties:
                ada:componentType:
                  anyOf:
                  - enum:
                    - ada:PSFDTabular
                  - ? ''
                    : ../adaProduct/schema.yaml#//universalComponentType
    schema:subjectOf:
      properties:
        dcterms:conformsTo:
          contains:
            type: object
            properties:
              '@id':
                const: 'https://w3id.org/geochem/metadata/profiles/adaPSFD'
