$schema: https://json-schema.org/draft/2020-12/schema
title: ADA L2MS Product Profile
description: Technique-specific profile for Two-Step Laser Mass Spectrometry (L2MS) products. Extends the base ADA product
  profile with constraints on valid L2MS component types and detailL2MS requirements.
allOf:
- $ref: ../adaProduct/schema.yaml
- type: object
  properties:
    schema:additionalType:
      description: Must include a L2MS product type identifier.
      contains:
        enum:
        - Microprobe Two-Step Laser Mass Spectrometry (L2MS)
        - Microprobe Two-Step Laser Mass Spectrometry
    schema:distribution:
      description: Distribution items for adaL2MS. Archive hasPart items must have ada:componentType from technique-specific
        or universal values.
      type: array
      items:
        type: object
        properties:
          schema:hasPart:
            items:
              type: object
              properties:
                ada:componentType:
                  anyOf:
                  - enum:
                    - ada:L2MSCube
                    - ada:L2MSOverviewImage
                  - ? ''
                    : ../adaProduct/schema.yaml#//universalComponentType
    schema:subjectOf:
      properties:
        dcterms:conformsTo:
          contains:
            type: object
            properties:
              '@id':
                const: 'https://w3id.org/geochem/metadata/profiles/adaL2MS'
