$schema: https://json-schema.org/draft/2020-12/schema
title: EA-IRMS Instrument Detail
description: Elemental Analysis Isotope Ratio Mass Spectrometry collection
type: object
properties:
  "@type":
    const: "ada:EAIRMSCollection"
  'ada:massConsumed':
    type: string
  'ada:elementType':
    type: string
