$schema: https://json-schema.org/draft/2020-12/schema
title: ADA RAMAN Product Profile
description: Technique-specific profile for Raman Spectroscopy (RAMAN) products. Extends the base ADA product profile with
  constraints on valid RAMAN component types.
allOf:
- $ref: ../adaProduct/schema.yaml
- type: object
  properties:
    schema:additionalType:
      description: Must include a RAMAN product type identifier.
      contains:
        const: Raman vibrational spectroscopy
    schema:distribution:
      description: Distribution items for adaRAMAN. Archive hasPart items must have ada:componentType from technique-specific
        or universal values.
      type: array
      items:
        type: object
        properties:
          schema:hasPart:
            items:
              type: object
              properties:
                ada:componentType:
                  anyOf:
                  - enum:
                    - ada:RAMANRawTabular
                  - ? ''
                    : ../adaProduct/schema.yaml#//universalComponentType
    schema:subjectOf:
      properties:
        dcterms:conformsTo:
          contains:
            type: object
            properties:
              '@id':
                const: 'https://w3id.org/geochem/metadata/profiles/adaRAMAN'
