$schema: https://json-schema.org/draft/2020-12/schema
title: L2MS Instrument Detail
description: Laser-2 Mass Spectrometry cube data with ionization parameters
type: object
properties:
  "@type":
    type: array
    contains:
      const: "ada:L2MSCube"
    minItems: 1
  'ada:sampleName':
    type: string
  'ada:ionizationTimeDelay':
    type: integer
  'ada:massGate':
    type: boolean
  'ada:photoionizationWavelength':
    type: integer
  'ada:plasmaShutter':
    type: boolean
  'ada:timeDelayUnits':
    type: string
  'ada:wavelengthUnits':
    type: string
